name: storybook link comment

on: pull_request

permissions:
  pull-requests: write

jobs:
  chromatic-link-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Storybook Link
        uses: dannyhw/storybook-chromatic-link-comment@v0.6
        with:
          app-id: 618d44792e48fd003a482f88
          github-token: ${{ secrets.GITHUB_TOKEN }}
